### ISSUE TITLE
Consider adding a link to your portfolio

### ISSUE THREAD

**Issue by Colnup** [prof-redstone/portes-folios-V3#1]
This repo hosts the source code of your portfolio, but no quick link to an hosted version.
As the title says, consider adding a link to the repo's "about" page on the top right.

**Comment by prof-redstone** [comment]
Oui webhost n'a plus son offre gratuite, je payerai plus tard, j'ai d'autres projets là Le 8 oct. 2024 11:24, Colin ***@***.***> a écrit :
This repo hosts the source code of your portfolio, but no quick link to an hosted version.
As the title says, consider adding a link to the repo's "about" page on the top right.

**Comment by prof-redstone** [comment]
hop la page
